import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" className={`${geistSans.variable} ${geistMono.variable} 
      bg-gradient-to-br from-zinc-900 to-zinc-950 text-gray-300 dark grid min-h-screen grid-rows-[auto_1fr]`}
      >
        <header className="flex justify-center p-5 border-b bg-zinc-800">
          <nav className="flex items-center justify-between gap-2 font-semibold container">
            <Link className="inline-flex items-center hover:text-gray-400" href={"/"}>
            <Image alt="" width={50} height={50} src={"https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Pok%C3%A9_Ball_icon.svg/770px-Pok%C3%A9_Ball_icon.svg.png"} />
            <p className="text-sm">
            Pokédex
            </p>
            </Link>
          </nav>
        </header>
        <main className="h-full flex justify-center items-center">
        {children}
        </main>
      </body>
    </html>
  );
}
